port:  5000
markdown: kramdown
name: "My Reps"
url: https://findmyreps.datamade.us
encoding: utf-8
timezone: America/Chicago
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyD7DTW1auNFO7VVEu_tK1-2dWWgXqaxXaQ
