port:  5000
markdown: kramdown
name: "My Reps"
url: https://acrincoli.github.io/my-reps/
encoding: utf-8
timezone: America/Chicago
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyCKvb0HmrMw0qg_0l5yokVMq9GYIwtahVQ
